### PR TITLE
fix: Update command messages to match feature list

### LINKED ISSUE #125: BUG: Command messages do not follow feature list docs
As stated in title.

### PR DESCRIPTION
**Pull request by allisonllx**
Builds upon #167 

Closes #125

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ViewCommandParser.java [hunk 1]
```diff
@@ -17,12 +16,16 @@ public class ViewCommandParser implements Parser<ViewCommand> {
      * @throws ParseException if the user input does not conform the expected format
      */
     public ViewCommand parse(String args) throws ParseException {
+        if (args == null || args.trim().isEmpty()) {
+            throw new ParseException(Messages.getCommandErrorWithUsage(
+                    Messages.MESSAGE_MISSING_INDEX, ViewCommand.MESSAGE_USAGE));
+        }
```
Comment (Cxyu629) [inline src/main/java/seedu/address/logic/parser/ViewCommandParser.java]: Prefer the below structure, also args does not need to be null-checked, otherwise an assertion would be a better fit.

```suggestion
        assert args != null;
        if (args.isBlank()) {
            throw new ParseException(Messages.getCommandErrorWithUsage(
                    Messages.MESSAGE_MISSING_INDEX, ViewCommand.MESSAGE_USAGE));
        }
```

File: src/main/java/seedu/address/logic/Messages.java [hunk 2]
```diff
@@ -51,4 +53,25 @@ public static String format(Contact contact) {
         return builder.toString();
     }
 
+    /**
+     * Returns a range message for 1-indexed contact list indices.
+     */
+    public static String getIndexOutOfRangeMessage(int maxIndex) {
```
Comment (Cxyu629) [inline src/main/java/seedu/address/logic/Messages.java]: Prefer naming it `formatIndexOutOfRange`.
```suggestion
    public static String formatIndexOutOfRange(int maxIndex) {
```

File: src/main/java/seedu/address/logic/Messages.java [hunk 3]
```diff
@@ -51,4 +53,25 @@ public static String format(Contact contact) {
...
+        return String.format("INDEX should be between 1 and %d", maxIndex);
```
Comment (Cxyu629) [inline src/main/java/seedu/address/logic/Messages.java]: Should make it a static final string.

File: src/main/java/seedu/address/model/ModelManager.java [hunk 4]
```diff
@@ -162,7 +170,15 @@ public void filterDisplayedContactList(Predicate<Contact> predicate) {
     @Override
     public void sortDisplayedContactList(Comparator<Contact> comparator) {
         requireNonNull(comparator);
-        sortedContacts.setComparator(comparator);
+
```
Comment (Cxyu629) [inline src/main/java/seedu/address/model/ModelManager.java]: Original code was intended behaviour.
