### PR TITLE
fix: Update wrongly-named reminder variables

### LINKED ISSUE #120: [BUG]: Outdated names for reminders/notes
Should comb through code to ensure standardization of namings between notes <-> reminders according to the newest info, i.e. that reminders are `Note`s that contain a non-null `TimePoint`.

On that note, prefer to use `Optional<TimePoint>` rather than null values if notes don't contain a reminder timepoint.

### PR DESCRIPTION
**Pull request by JustATin555**
- Rename `ReminderLabel` to `NoteLabel`
- Update `NoteLabel` fields

Fixes #120

### CODE REVIEW

File: src/main/java/seedu/address/ui/NoteLabel.java [hunk 1]
```diff
@@ -22,16 +22,16 @@
  */
 public class NoteLabel extends HBox {
 
-    private static final String FXML = "/view/ReminderLabel.fxml";
+    private static final String FXML = "/view/NoteLabel.fxml";
 
     @FXML
-    private Label reminderHeader;
+    private Label header;
```
Comment (deltaMinor) [inline src/main/java/seedu/address/ui/NoteLabel.java]: Isn't it more accurate to keep the name `reminderHeader` as it is designated to contain only the text "Reminder:" and appear when the note acts as a reminder?
