### PR TITLE
fix: Make notes section of contact card scrollable, add indexes to notes section in Contact Detail Panel

### LINKED ISSUE #330: [PE-D][Tester D] UI : Showcase of index of note for users to delete or edit notes easier
## Description of Flaw
Provided that the application is targeted towards fast typists, according to the user guide, editing a note follows the format of `note INDEX el/NOTE_INDEX NEW_NOTE [on/TIME] and deleting a note follows the format `note INDEX cl/NOTE_INDEX`. As such, given that a person may have multiple notes, in the scenario where for example, the user has more than 15 or 20 notes, to count the note number to delete or edit manually may be time consuming for the user. 

Image

In the figure above, if the user wants to delete one of the notes in the middle of the list, the user would need to count from the top which may be a hassle.

## Suggested Improvement
As such, showing the index of the note beside the note itself would allow for users to refer to the person list and know the note index quickly, allowing for faster use of the application.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #341: [PE-D][Tester D] UI: Person card cuts off any notes added after the third note
## Description of Bug
When a large number of notes are added, only until the second note and half of the third note can seen in the person card. Although the team has implemented a well functioning view function, implementing scrolling in the person card would make the UI look more full as well. For example in the image below, note 4 is cut off. Although this does not affect functioning, this is merely a small fix that the group could look into to further solidify their application.
Image

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`

### LINKED ISSUE #349: [PE-D][Tester B] [Bug] View panel - shows more information than the PersonCard
### Description

The PersonCard shows the brief details about that contact. However, when there are too many details added, some of the details are missing in the PersonCard. By default, the view panel is closed. The user might miss out details if the view panel is not open when he is looking at the contacts at the point of using B2B4U.

Image

### Suggestion
Add 3 dots `...` or a 'open view panel to view more' text in the PersonCard so that the user knows that there are more details not being shown.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by deltaMinor**
Resolves #330 
Resolves #341 
Resolves #349
## Changes
- Make notes section scrollable in ContactCard
  - Justification:
    - To resolve #341 and #349
    - I don't know how to implement the ellipses thing with Textflow, so this is easier.
    - This does not make the Contact Detail Panel redundant however due to the following change
- Add indexes to notes section in Contact Detail Panel
  - Resolves #330
- Make entirety of details in Contact Detail Panel scrollable
  - Makes the scrollbar easier to use

### CODE REVIEW

File: src/main/java/seedu/address/ui/ContactDetailPanel.java [hunk 1]
```diff
@@ -112,9 +112,14 @@ public void setContact(Contact contact) {
...
-            notesTextFlow.addStyleClass("detail-text-flow");
-            notesScrollPane.setContent(notesTextFlow);
+            contact.getNotes()
+                    .forEach(note -> {
+                        NoteLabel noteLabel = new NoteLabel(note, notes.getStyleClass().toString(), allContacts);
+                        noteLabel.hideHeader();
+                        Label indexLabel = new Label((notes.getChildren().size() + 1) + ". ");
+                        indexLabel.getStyleClass().add("note-index-label");
+                        HBox indexedNoteLabel = new HBox(indexLabel, noteLabel);
+                        notes.getChildren().add(indexedNoteLabel); });
```
Comment (JustATin555) [inline src/main/java/seedu/address/ui/ContactDetailPanel.java:123]: Image

Seems to cause note duplication in contact detail panel? I suspect this line but cannot confirm...

**Review by JustATin555 — CHANGES_REQUESTED** [review]
Notes get appended to contact detail panel every time it is opened.

To reproduce:
1. Have 1 or more notes in a contact
2. Open the view panel
3. Close the view panel
4. Repeat steps 2-3 as many times as necessary

File: src/main/java/seedu/address/ui/ContactDetailPanel.java (hunk 1 above)
Comment (deltaMinor) [reply src/main/java/seedu/address/ui/ContactDetailPanel.java:123]: Forgot to clear notes children before addition, fixed in [33f5dfe](https://github.com/AY2526S2-CS2103T-T08-1/tp/pull/380/commits/33f5dfe28c8b504a05f303c388b57820d8bd391d)

**Review by JustATin555 — APPROVED** [review]
LGTM
