### PR TITLE
Fix NoteClearCommand and NoteClearAllCommand success messages

### LINKED ISSUE #218: BUG: NoteClearCommand and NoteClearAllCommand display wrong success message
## Description
Both NoteClearCommand and NoteClearAllCommand have MESSAGE_REMOVE_NOTES_SUCCESS = 'Edited note' which is a copy-paste error. The message should reflect the actual operation (clearing notes).

## Steps to Reproduce
1. Add some notes to a contact: note 1 Hello
2. Clear notes: note 1 co/1
3. Or clear all: note 1 ca/

## Expected Behaviour
Feedback should say 'Cleared notes' or 'Cleared all notes'.

## Actual Behaviour
Feedback says 'Edited note' which is confusing and incorrect.

## Location
- NoteClearCommand.java line 20
- NoteClearAllCommand.java line 19

### PR DESCRIPTION
**Pull request by p12010304**
Both commands had MESSAGE_REMOVE_NOTES_SUCCESS = 'Edited note' due to a copy-paste error. Changed to 'Cleared notes' and 'Cleared all notes' respectively.

Also fixed NoteClearCommandTest referencing the wrong class constant.

Fixes #218

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/NoteClearCommand.java [hunk 1]
```diff
@@ -17,7 +17,7 @@
  */
 public class NoteClearCommand extends NoteCommand {
 
-    public static final String MESSAGE_REMOVE_NOTES_SUCCESS = "Edited note";
+    public static final String MESSAGE_REMOVE_NOTES_SUCCESS = "Cleared notes";
```
Comment (Cxyu629) [inline src/main/java/seedu/address/logic/commands/NoteClearCommand.java]: Maybe "Cleared 12 notes"? Where 12 is the numLines for example.
